import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast';
import dotenv from 'dotenv';
import { StoreProvider } from '@/store/StoreProvider';
dotenv.config();


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <StoreProvider >
            <html lang="en">
                <body className={inter.className}>
                    <Toaster position='top-right' />
                    <main>
                        {children}
                    </main>
                </body>
            </html>
        </StoreProvider>
    )
}
